obstacle_range: 3.0
raytrace_range: 3.5
footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
map_topic: /map
subscribe_to_updates: true
obstacle_layer: {observation_sources: laser_scan_sensor,origin_z: 0.0, laser_scan_sensor: {sensor_frame: base_scan, data_type: LaserScan, topic: /scan, marking: true, clearing: true}}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
cost_scaling_factor: 6.0
