pure_pursuit_controller:
  min_lookahead: 0.2
  max_lookahead: 2.5
  # closest_point_index_search depends on the number of points in path per meter
  # Value equal to number of points in 1~2 meter may be a good param value  
  closest_point_index_search: 10.0
  max_acceleration: 0.5
  max_vel: 0.2
  min_vel: 0.1
  max_omega: 2.5
  max_turn_radius: 2
  min_turn_radius: 0.1
  max_radius_omega: 20.0
  max_y_deviation: 0.1  
  max_path_deviation: 1.0
  max_theta_deviation: 0.5
  transform_tolerance: 0.5
  holonomic_robot: false
  drive_type: 'differential'
  on_the_spot_turn_allowed: false